version: "3.8"

# notes:
# "ports SOME_PUBLICPORT:SOME_INTERNALPORT" sets up a forwarding from host (aka ouside world) to internal docker network
# "expose SOME_INTERNALPORT" is only for documentation / metadata on the container. set this to the port that the service is using.
# communicate between services with protocol://servicename:INTERNALPORT eg http://api:3002 or mysql://someusername:somepassword@db:3306/db

services:
  db:
    #image: mysql:8.0
    image: andersgee/http-mysql8-sqlx:0.3
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      #- 4000:3000
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  db-data:
